# server
server:
  port: 8080

# sprig configs
spring:
  application:
    name: codechella

  datasource:
    url: jdbc:postgresql://${DB_HOST}/codechella_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect